name: "I2C OLED Display"
description: "This addon lets you display to your I2C OLED for a Raspberry Pi with an I2C SSD1306 0.91\" 128x64 OLED."
version: "0.0.1"
slug: "i2c_oled_display"
startup: services
boot: manual
hassio_api: true
init: false
auth_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - media:rw
devices:
  - /dev/i2c-0
  - /dev/i2c-1
  - /dev/i2c-2
  - /dev/i2c-3
  - /dev/i2c-4
  - /dev/i2c-5
  - /dev/i2c-6
  - /dev/i2c-7
  - /dev/i2c-8
  - /dev/i2c-9
  - /dev/i2c-10
  - /dev/i2c-11
  - /dev/i2c-12
  - /dev/i2c-13
  - /dev/i2c-14
  - /dev/i2c-15
  - /dev/i2c-16
  - /dev/i2c-17
  - /dev/i2c-18
  - /dev/i2c-19
  - /dev/i2c-20
options:
  Show_Network_Screen: true
  Show_CPU_Screen: true
  Show_Memory_Screen: true
  Show_Storage_Screen: true

  Default_Duration: 10
  DateTime_Format: "%d/%m/%Y %H:%M:%S"
  Temperature_Unit: "C"

  Network_Screen_Duration: 10
  Network_Screen_Limit: 0

  CPU_Screen_Duration: 5
  CPU_Screen_Limit: 0

  Memory_Screen_Duration: 5
  Memory_Screen_Limit: 0

  Storage_Screen_Duration: 5
  Storage_Screen_Limit: 0

  Supervizor_token: ''

  Debug_Mode: false
  I2C_bus: 1
  Screenshot: ''

schema:	
  Show_Network_Screen: bool
  Show_CPU_Screen: bool
  Show_Memory_Screen: bool
  Show_Storage_Screen: bool
 
  Default_Duration: int
  DateTime_Format: "str?"
  Temperature_Unit: "list(C|F)?"

  Network_Screen_Duration: "int?"
  Network_Screen_Limit: "int?"

  CPU_Screen_Duration: "int?"
  CPU_Screen_Limit: "int?"

  Memory_Screen_Duration: "int?"
  Memory_Screen_Limit: "int?"

  Storage_Screen_Duration: "int?"
  Storage_Screen_Limit: "int?"

  Debug_Mode: bool
  I2C_bus: "int(0,20)"
  Screenshot: "list(|/media)"

  Supervizor_token: "str?"
